# Generated by Django 3.2.8 on 2021-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='项目id', primary_key=True, serialize=False, verbose_name='项目id')),
                ('name', models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('programmer', models.CharField(help_text='开发负责人', max_length=50, verbose_name='开发负责人')),
                ('publish_app', models.CharField(help_text='发布应用', max_length=50, verbose_name='发布应用')),
                ('desc', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'tb_projects',
            },
        ),
    ]
