# Generated by Django 3.2.8 on 2021-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envs',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='环境名称', max_length=200, verbose_name='环境名称')),
                ('baseurl', models.URLField(help_text='请求的base_url', max_length=300, verbose_name='请求的base_url')),
                ('desc', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='环境描述')),
            ],
            options={
                'verbose_name': '项目的全局环境变量配置表',
                'verbose_name_plural': '项目的全局环境变量配置表',
                'db_table': 'tb_envs',
            },
        ),
    ]
